# 应用配置
app:
  name: "智能选股系统"
  version: "1.0.0"
  env: "development"
  port: 8080
  debug: true
  
# 服务器配置
server:
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

# 数据库配置
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "stock_db"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# 日志配置
log:
  level: "info"
  format: "json"
  file: "logs/app.log"
  max_size: 100
  max_backups: 7
  max_age: 30
  compress: true

# JWT配置
jwt:
  secret: "your_jwt_secret_here"
  expire_hours: 24
  issuer: "stock"

# 限流配置
rate_limit:
  enabled: true
  rps: 100
  burst: 200

# 监控配置
metrics:
  enabled: true
  port: 9090
  path: "/metrics"

# CORS配置
cors:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]
  exposed_headers: []
  allow_credentials: true
  max_age: 86400